### ISSUE TITLE
Gulp tasks break if the `USER` environment variable is set

### ISSUE THREAD

**Issue by francoishill** [websysd/websysd#5]
The `AddDefaultVars` method sets the `USER` variable. This causes `gulp` tasks to fail with this error:

```
Unable to cache a config file for v8flags to a your home directory
or a temporary folder. To fix this problem, please correct your
environment by setting HOME=/path/to/home or TEMP=/path/to/temp.
NOTE: the user running this must be able to access provided path.
If all else fails, please open an issue here:
http://github.com/tkellen/js-v8flags
    at Error (native)
```

Commenting out the line `vars["USER"] = u.Username` solves the problem for now.

**Comment by ian-kent** [comment]
Thanks @francoishill, but this seems like a bug with gulp? Not sure why setting `USER` would stop gulp finding the home directory or temporary directory, and its setting it to the username which is what `USER` would be by default anyway?
